### ISSUE TITLE
someone copying your project and uploading it on google web store

### ISSUE THREAD

**Issue by zainullahk** [rkodey/the-great-er-discarder-er#10]
https://chrome.google.com/webstore/detail/the-great-er-discarder-er/ebobjnbkjkanckcpnciegjfdndooflbe

**Comment by albertstartup** [comment]
Can confirm as well.
Going to report it on the Chrome Store.

**Comment by bryancasler** [comment]
I was going to report it too but it doesn't seem to violate any of the Chrome Store policies

**Comment by rkodey** [comment]
Thanks for the heads-up...  although that's essentially what I did with the original abandoned project when I forked it.  Hmm - I'm not sure there's much to be done.  Flattered...  I guess?

**Comment by bryancasler** [comment]
Maybe they did it just so they could have full control over code (chrome extensions) they allow their staff to install and use?
