### ISSUE TITLE
What really has been changed to justify rename?

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [rkodey/the-great-er-discarder-er#2]
I appreciate your effort - but isn't it a bit too early to claim it?

Can you please tell a bit about what you have improved and what are you plans for the nearest future.

**Comment by rkodey** [comment]
Hi.  The original author hasn't made any changes in 4 years, and got himself into a bit of trouble with his other plugin "The Great Suspender".  There were enough users questioning the fate of this plugin, that I just thought I'd give it a go.  The timing seems justified given it appears abandoned and pull requests done unanswered.

The main enhancement I've made so far is to add a setting to prevent Chrome from pre-loading all open tabs at startup.  My intention is to merge in other open pull requests and keep a bit of evolution going.
