### ISSUE TITLE
Interest in TypeScript rewrite? 

### ISSUE THREAD

**Issue by phil-lgr** [rkodey/the-great-er-discarder-er#7]
I found that this extension works fine. Sometimes, for windows that are minimized, it does not.

I'd want to help out and debug, but I have the rule that I don't touch a project written in plain JS, it's just too much pain.

The project is small right now and could be converted in TS, making the project more robust, I'm pretty sure we could fix issues just by converting it

Are you open to that?

Thanks,

**Comment by rkodey** [comment]
Hi Phil-  I honestly wish I had the time!  I republished this fork with the intention of adding a few additional features, but I haven't gone much past the initial feature of preventing Chrome from loading all tabs at startup.

If I/we had lots of new features planned then it probably would make sense to convert it.  I guess my overall thought is that this discarder extension is simple enough that I'm not sure there's much value in doing the conversion.  I don't know, I guess...  do you see this extension growing much?

I'm new enough to TS that I don't have a feel for the scope of work for the conversion, though.  Are there tools to help out?
