### ISSUE TITLE
Deploying setting by GPO

### ISSUE THREAD

**Issue by RockingKozaK** [rkodey/the-great-er-discarder-er#8]
Hello, I need to find an extention that allows me to define default settings for a lot of people in a single click (I'm a system administrator and need to add my softphone and some other stuff to the whitelist to avoid chome to suspend it) is it possible with your extension ?
I did it formerly with the great suspender using the register
![TMS](https://user-images.githubusercontent.com/89450507/130601701-52e09ff2-037d-4ad8-b4a6-4e93fa68b0c9.png)
Thank you by advance for your help

**Comment by rkodey** [comment]
I think that would be a function of Chrome, not for individual extensions.  That said, if you export those settings into a .REG file, I'm fairly sure you can deploy registry files to apply to groups of users via GPO.  I've never tried that myself, so you should probably experiment with a small set of users at first.

**Comment by CruxHelloDonor** [comment]
Where are the settings stored in the registry for the great er discarder er?

**Comment by rkodey** [comment]
Browser extension settings are not stored in the registry at all.  What you see above is a way to deploy default settings that will be applied when the extension is first installed.  After that, the browser stores settings locally.

**Comment by CruxHelloDonor** [comment]
I don't see anything above that tells me how to apply your default settings.   Or are those registry settings listed above what would work with YOUR extension?

**Comment by RockingKozaK** [comment]
I had to find an other way to do it, chrome is now doing it natively, and it's manageable with GPO
thanks for your answers

**Comment by RockingKozaK** [comment]
so subject close
